Update spell.yml

diff --git a/.github/workflows/spell.yml b/.github/workflows/spell.yml
--- a/.github/workflows/spell.yml
+++ b/.github/workflows/spell.yml
@@ -41,13 +41,11 @@ jobs:
           # use cargo binstall
           tool: ripgrep
 
-    
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
 
       # Runs a single command using the runners shell
       - name: Search, saving results to a json lines file
-        run: rg -i "${{env.match-regex}}" ./ -g "*.{js,jsx,ts,tsx,md,mdx,yaml,yml}" --json | tee matches.jsonl
+        run: rg -i "${{env.match-regex}}" ./ -g "*.{js,jsx,ts,tsx,md,mdx,yaml,yml}" --json | tee matches.jsonl | sed -e "s/^/::debug::/" -
 
       - name: Parse Results
         run: |
@@ -78,7 +76,7 @@ jobs:
                 col_end=$(echo "$json" | jq -r --argjson index "$index" '.data.submatches[$index].end')
                 echo "::debug::for submatch i=${index} / n=${submatches_count}: text=${matched_text} col=${col_start}:${col_end}"
                 
-                echo "::error file=${file_name},line=${line_number},endLine=${line_number},col=${col_start},endColumn=${col_end},title=Wrong spelling found: \"${matched_text}\"::\"${matched_text}\" found in ${file_name}#${line_number}.\r\n(try looking in a dictionary for the american alternative)" || true
+                echo "::error file=${file_name},line=${line_number},endLine=${line_number},col=${col_start},endColumn=${col_end},title=Wrong spelling found: \"${matched_text}\"::\"${matched_text}\" found in ${file_name}#${line_number}.\\r\\n(try looking in a dictionary for the american alternative)" || true
                 ((matches++)) || true
               done
             else
