Update spell.yml

diff --git a/.github/workflows/spell.yml b/.github/workflows/spell.yml
--- a/.github/workflows/spell.yml
+++ b/.github/workflows/spell.yml
@@ -8,7 +8,7 @@ env:
 # Controls when the workflow will run
 on:
   push:
-    paths: ["*.js","*.jsx","*.ts","*.tsx","*.md","*.mdx","*.yaml","*.yml"]
+    paths: ["**/*.js","**/*.jsx","**/*.ts","**/*.tsx","**/*.md","**/*.mdx","**/*.yaml","**/*.yml"]
   pull_request:
     types: 
       - opened
@@ -16,7 +16,7 @@ on:
       - reopened
       - synchronize
       
-    paths: ["*.js","*.jsx","*.ts","*.tsx","*.md","*.mdx","*.yaml","*.yml"]
+    paths: ["**/*.js","**/*.jsx","**/*.ts","**/*.tsx","**/*.md","**/*.mdx","**/*.yaml","**/*.yml"]
 
   # tmp: manual run
   workflow_dispatch:
@@ -29,7 +29,13 @@ jobs:
 
     
     steps:
-      # TODO setup cache
+
+      - uses: Swatinem/rust-cache@v2
+        with:
+          # doesnt affect binary downloaded
+          cache-on-failure: true
+          
+      
       - uses: taiki-e/install-action@v2
         with:
           # use cargo binstall
@@ -46,15 +52,15 @@ jobs:
       - name: Parse Results
         run: |
           # Gets Results from rg json output, formats it how github wants.
-          echo "Starting parsing"
+          echo ::debug::"Starting parsing"
           matches=0
           while IFS="" read -r json || [ -n "$json" ]; do
             
             # only for match types (ignoring start file, end file, summary)
             type=$(echo "$json" | jq -r '.type')
-            echo "got line of type=${type}"
+            echo "::debug::got line of type=${type}"
             if [ "$type" != "match" ]; then
-              echo "skipping..."
+              echo "::debug::skipping..."
               continue
             fi
             
@@ -64,24 +70,23 @@ jobs:
 
             # Looping over submatches
             submatches_count=$(echo "$json" | jq -r '.data.submatches | length')
-            echo "got n=${submatches_count} matches for line=${line_number} in file=${file_name}"
+            echo "::debug::got n=${submatches_count} matches for line=${line_number} in file=${file_name}"
             if [ "$submatches_count" -gt 0 ]; then
               for index in $(seq 0 $((submatches_count - 1))); do
                 matched_text=$(echo "$json" | jq -r --argjson index "$index" '.data.submatches[$index].match.text')
                 col_start=$(echo "$json" | jq -r --argjson index "$index" '.data.submatches[$index].start')
                 col_end=$(echo "$json" | jq -r --argjson index "$index" '.data.submatches[$index].end')
-                echo "for submatch i=${index} / n=${submatches_count}: text=${matched_text} col=${col_start}:${col_end}"
+                echo "::debug::for submatch i=${index} / n=${submatches_count}: text=${matched_text} col=${col_start}:${col_end}"
                 
-                echo "::error file=${file_name},line=${line_number},endLine=${line_number},col=${col_start},endColumn=${col_end},title=Wrong spelling found: \"${matched_text}\"::Wrong spelling found: \"${matched_text}\".\\n(try looking in a dictionary for the american alternative)" || true
+                echo "::error file=${file_name},line=${line_number},endLine=${line_number},col=${col_start},endColumn=${col_end},title=Wrong spelling found: \"${matched_text}\"::Wrong spelling found: \"${matched_text}\". (try looking in a dictionary for the american alternative)" || true
                 ((matches++)) || true
               done
-              echo "test2"
             else
               # should never happen
-              echo ::error title=Unexpected Data::Unexpected Data found: match json has empty sub-matches:\\n${json}
+              echo ::error title=Unexpected Data::Unexpected Data found: match json has empty sub-matches ${json}
             fi
           done < matches.jsonl
-          echo "Completed."
+          echo "::debug::Completed."
           if [ "$matches" -eq 0 ]; then
             # success
             echo "Success: No matches found!"
