Update spell.yml

diff --git a/.github/workflows/spell.yml b/.github/workflows/spell.yml
--- a/.github/workflows/spell.yml
+++ b/.github/workflows/spell.yml
@@ -72,9 +72,11 @@ jobs:
                 col_end=$(echo "$json" | jq -r --argjson index "$index" '.data.submatches[$index].end')
                 echo "for submatch i=${index} / n=${submatches_count}: text=${matched_text} col=${col_start}:${col_end}"
                 
-                echo "::error file=${file_name},line=${line_number},endLine=${line_number},col=${col_start},endColumn=${col_end},title=Wrong spelling found: \"${matched_text}\"::Wrong spelling found: \"${matched_text}\".\n(try looking in a dictionary for the american alternative)"
+                echo "::error file=${file_name},line=${line_number},endLine=${line_number},col=${col_start},endColumn=${col_end},title=Wrong spelling found: \"${matched_text}\"::Wrong spelling found: \"${matched_text}\".\\n(try looking in a dictionary for the american alternative)" || true
+                echo "test"
                 ((matches++))
               done
+              echo "test2"
             else
               # should never happen
               echo ::error title=Unexpected Data::Unexpected Data found: match json has empty sub-matches:\\n${json}
